# @package _global_
module:
  _target_: emg2qwerty.lightning.GRUCTCModule
  in_features: 528
  mlp_features: [192]
  gru_hidden_size: 128
  num_gru_layers: 4
  block_channels: [12, 12, 12, 12]
  kernel_width: 32

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
